In [1]:
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
x = np.array([1, 2, 3, 4, 5, 6])

In [3]:
print(x)

[1 2 3 4 5 6]


In [4]:
x[0]

1

In [5]:
x[2]

3

In [6]:
y = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
y[0, 2]

3

In [8]:
y[1]

array([5, 6, 7, 8])

In [9]:
y[:, 1] 

array([ 2,  6, 10])

In [10]:
# Display the first row of the array
print("Displaying the first row:")
print(y[0, :])

# Show the last two elements in the first row
print("Showing the last two elements in the first row:")
print(y[0, -2:])

# Retrieve every second element in the first row
print("Retrieving every second element in the first row:")
print(y[0, ::2])

# Extract a submatrix from the original array
print("Extracting a submatrix:")
print(y[:2, 1:3])

Displaying the first row:
[1 2 3 4]
Showing the last two elements in the first row:
[3 4]
Retrieving every second element in the first row:
[1 3]
Extracting a submatrix:
[[2 3]
 [6 7]]


In [11]:
z = np.arange(2, 9, 2)
print(z)

[2 4 6 8]


In [12]:
w = np.arange(11)
print(w)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [13]:
x = np.linspace(0, 10, num=20)
print(x)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [14]:
print(x[x > 7])

[ 7.36842105  7.89473684  8.42105263  8.94736842  9.47368421 10.        ]


In [15]:
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
y.ndim

2

In [17]:
print(y.max(axis=1))

[ 4  8 12]


In [18]:
print(y.max(axis=0))

[ 9 10 11 12]


In [19]:
y.shape

(3, 4)

In [20]:
m = np.array([1.62, 1.75, 1.55, 1.74])
kg = np.array([55.4, 73.6, 57.1, 59.5])

print(m)
print(kg)

[1.62 1.75 1.55 1.74]
[55.4 73.6 57.1 59.5]


In [21]:
55.4 / 1.62**2

21.109586953208346

In [22]:
kg[0] / m[0]**2

21.109586953208346

In [23]:
bmi = kg / m**2

In [24]:
bmi.round(1)

array([21.1, 24. , 23.8, 19.7])

In [25]:
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
result = y * 2
print(result)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [27]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [28]:
[x.min(), x.max(), x.sum(), x.mean(), x.std()]

[1, 3, 6, 2.0, 0.816496580927726]

In [29]:
print(x)

[1 2 3]


In [30]:
np.sqrt(np.sum((x - np.mean(x)) ** 2) / np.size(x))

0.816496580927726

In [31]:
np.mean(x)

2.0

In [32]:
x - np.mean(x)

array([-1.,  0.,  1.])

In [33]:
(x - np.mean(x)) ** 2

array([1., 0., 1.])

In [34]:
np.sum((x - np.mean(x)) ** 2)

2.0

In [35]:
res = np.sum((x - np.mean(x)) ** 2) / np.size(x)
res

0.6666666666666666

In [36]:
np.sqrt(res)

0.816496580927726

In [37]:
np.std(x)

0.816496580927726

In [38]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
y = x[:2, 1:3]
print(y)

[[2 3]
 [6 7]]


In [40]:
print(x[0, 1])   

2


In [41]:
y[0, 0] = 77     


In [42]:
print(x)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

z = x.copy()
print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [44]:
z[0, 1] = 33
print(z)

[[ 1 33  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
%load_ext watermark
%watermark -n -u -v -iv -w -p pytensor

Last updated: Sun Sep 17 2023

Python implementation: CPython
Python version       : 3.11.5
IPython version      : 8.15.0

pytensor: 2.12.3

numpy: 1.25.2

Watermark: 2.4.3

