In [1]:
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [5]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)


(array([0, 1, 4]),)


In [6]:
Z = np.random.random((10,10))
Z

array([[0.0708204 , 0.95974688, 0.4672839 , 0.41922607, 0.98598493,
        0.63473662, 0.78101736, 0.072342  , 0.49436298, 0.20856603],
       [0.70646236, 0.91179868, 0.62443811, 0.9215931 , 0.0655805 ,
        0.94999081, 0.03188679, 0.53062703, 0.4437942 , 0.92951406],
       [0.43417452, 0.58559374, 0.72067867, 0.22881332, 0.12704034,
        0.82579505, 0.35690228, 0.75433483, 0.14171088, 0.72261857],
       [0.06762427, 0.99049463, 0.57682744, 0.75731278, 0.54196812,
        0.46814389, 0.67032553, 0.32896111, 0.75681843, 0.61696947],
       [0.54431492, 0.72534886, 0.47978425, 0.8639504 , 0.84069558,
        0.03679093, 0.93505434, 0.44160958, 0.48523031, 0.68891511],
       [0.16887746, 0.25311054, 0.82361984, 0.77013944, 0.10064537,
        0.93515197, 0.99096414, 0.50058185, 0.99326829, 0.631005  ],
       [0.41192784, 0.45320375, 0.17977229, 0.67765087, 0.1319186 ,
        0.8403485 , 0.76193093, 0.86525157, 0.66634861, 0.34378106],
       [0.42722908, 0.88530912, 0.7458611

In [7]:
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.03188678958750113 0.9932682942858698


In [8]:
Z = np.random.random(30)
Z

array([0.48508621, 0.17234104, 0.49710369, 0.058412  , 0.32280899,
       0.44068946, 0.31127164, 0.91661934, 0.40799206, 0.99502268,
       0.70209845, 0.6785909 , 0.72484677, 0.55229031, 0.50926366,
       0.56562666, 0.34770023, 0.50786573, 0.37492836, 0.61136544,
       0.51608351, 0.5528491 , 0.2971558 , 0.79799982, 0.1292703 ,
       0.77011866, 0.02108276, 0.79124021, 0.75452956, 0.97990278])

In [9]:
m = Z.mean()
print(m)

0.5264052039328897


In [10]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [11]:
print(sum(range(5),-1))

9


In [12]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.26073755 0.07938285 0.11947669 0.01694249 0.43450715 0.09003104
 0.52898779 0.21089765 0.58457833 0.        ]


In [13]:
Z = np.arange(100)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
v = np.random.uniform(0, 100)
v

83.56341911433401

In [15]:
index = (np.abs(Z - v)).argmin()
print(Z[index])


84


In [16]:
a = np.array([[2.5, 3.8, 1.5], [4.7, 2.9, 1.56]])

o = a.astype("int")

print(o)


[[2 3 1]
 [4 2 1]]


In [17]:
a = np.array([[1, 0, 0], [1, 1, 1], [0, 0, 0]])

o = a.astype("bool")

print(o)


[[ True False False]
 [ True  True  True]
 [False False False]]


In [18]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])

a2 = np.array([[7, 8, 9], [10, 11, 12]])

o = np.hstack((a1, a2))

print(o)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [19]:
a = np.array([1, 2, 3, 4, 5])

b = np.array([1, 3, 2, 4, 5])

print(np.where(a == b))


(array([0, 3, 4]),)


In [20]:
a = np.array([[1, 2, 3], [4, 5, 6]])

o = np.tile(a, 10)

print(o)


[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]


In [21]:
np.random.seed(123)  # setting the seed

o = np.random.randint(0, 10, size=(5, 5))

print(o)


[[2 2 6 1 3]
 [9 6 1 0 1]
 [9 0 0 9 3]
 [4 0 0 4 1]
 [7 3 2 4 7]]


In [22]:
x = np.array([1, 0, 0, 0])
print(np.any(x))
x = np.array([0, 0, 0, 0])
print(np.any(x))


True
False


In [23]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(np.equal(x, y))
print(np.allclose(x, y))


[ True  True  True  True  True  True  True  True  True False]
True


In [24]:
nums = np.array([[3, 2, np.nan, 1], [10, 12, 10, 9], [5, np.nan, 1, np.nan]])
nums



array([[ 3.,  2., nan,  1.],
       [10., 12., 10.,  9.],
       [ 5., nan,  1., nan]])

In [25]:
print(np.isnan(nums))

[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [26]:
nums = np.array([[5.54, 3.38, 7.99], [3.54, 4.38, 6.99], [1.54, 2.39, 9.29]])
n = 6
print(nums[nums < n])


[5.54 3.38 3.54 4.38 1.54 2.39]


In [27]:
nums = np.array([[5.54, 3.38, 7.99], [3.54, 8.32, 6.99], [1.54, 2.39, 9.29]])
n = 8.32
r = 18.32
print(np.where(nums == n, r, nums))

[[ 5.54  3.38  7.99]
 [ 3.54 18.32  6.99]
 [ 1.54  2.39  9.29]]


In [28]:
print("\nReplace elements with of the said array which are less than", n, "with", r)
print(np.where(nums < n, r, nums))


Replace elements with of the said array which are less than 8.32 with 18.32
[[18.32 18.32 18.32]
 [18.32  8.32 18.32]
 [18.32 18.32  9.29]]


In [29]:
print("\nReplace elements with of the said array which are greater than", n, "with", r)
print(np.where(nums > n, r, nums))


Replace elements with of the said array which are greater than 8.32 with 18.32
[[ 5.54  3.38  7.99]
 [ 3.54  8.32  6.99]
 [ 1.54  2.39 18.32]]


In [30]:
nums1 = np.array([[2, 5, 2], [1, 5, 5]])
nums2 = np.array([[5, 3, 4], [3, 2, 5]])


In [31]:
print(nums1)

[[2 5 2]
 [1 5 5]]


In [32]:
print(nums2)

[[5 3 4]
 [3 2 5]]


In [33]:
print(np.multiply(nums1, nums2))

[[10 15  8]
 [ 3 10 25]]
